function init() {
    var stores_data = [{
            "direccionId": 14,
            "usuarioId": 1,
            "direccion_Direccion": "Av. Agustin Gamarra 140",
            "direccionPiso": "1",
            "direccionTelefono": "",
            "direccionHorario": "8:00 - 9:00",
            "nombresComercial": "Victors Nombre Comercial",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_1.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_1.png",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "alumnodemichi",
            "sM_InstagramId": "victorbernedot",
            "sM_WhatsappId": "992269960",
            "latitude": -12.0641762,
            "longitude": -77.1525624
        },
        {
            "direccionId": 15,
            "usuarioId": 14,
            "direccion_Direccion": "Av Agustin Gamarra 650",
            "direccionPiso": "1",
            "direccionTelefono": "",
            "direccionHorario": "9:30 - 20:00",
            "nombresComercial": "Kayser",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/Mahna Mahna.jpg",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "kayser.peru",
            "sM_InstagramId": "kayserperu",
            "sM_WhatsappId": "999693860",
            "latitude": -12.0665232,
            "longitude": -77.01325109999999
        },
        {
            "direccionId": 16,
            "usuarioId": 16,
            "direccion_Direccion": "Av. Agustin Gamarra 1103",
            "direccionPiso": "1",
            "direccionTelefono": "01 3253107",
            "direccionHorario": "8:00 - 9:00",
            "nombresComercial": "Mya Line",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/GamarraAppLogoGoogle.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "myalinefitness",
            "sM_InstagramId": null,
            "sM_WhatsappId": null,
            "latitude": -12.0695634,
            "longitude": -77.0128069
        },
        {
            "direccionId": 17,
            "usuarioId": 16,
            "direccion_Direccion": "Av Agustin Gamarra 1105",
            "direccionPiso": "1",
            "direccionTelefono": "",
            "direccionHorario": "8:00 a 9:00",
            "nombresComercial": "Mya Line",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/GamarraAppLogoGoogle.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "myalinefitness",
            "sM_InstagramId": null,
            "sM_WhatsappId": null,
            "latitude": -12.0694625,
            "longitude": -77.0127509
        },
        {
            "direccionId": 18,
            "usuarioId": 17,
            "direccion_Direccion": "Av Agustin Gamarra 445",
            "direccionPiso": "1",
            "direccionTelefono": "01 345 3704",
            "direccionHorario": "8:00",
            "nombresComercial": "Pioner",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/GamarraAppLogoGoogle.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": null,
            "sM_InstagramId": null,
            "sM_WhatsappId": null,
            "latitude": -12.0652889,
            "longitude": -77.154501
        },
        {
            "direccionId": 19,
            "usuarioId": 18,
            "direccion_Direccion": "Av. Agustin Gamarra 1017",
            "direccionPiso": "1",
            "direccionTelefono": "01 3241407",
            "direccionHorario": "8:00 - 9:00",
            "nombresComercial": "Bata",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_18.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_18.png",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "BataPeru",
            "sM_InstagramId": "bata.peru",
            "sM_WhatsappId": "+51999693860",
            "latitude": -12.0684229,
            "longitude": -77.0128529
        },
        {
            "direccionId": 20,
            "usuarioId": 14,
            "direccion_Direccion": "Av. La Mar 2225 - San Miguel",
            "direccionPiso": "1",
            "direccionTelefono": "",
            "direccionHorario": "8:00 - 9:00",
            "nombresComercial": "Kayser",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/Mahna Mahna.jpg",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "kayser.peru",
            "sM_InstagramId": "kayserperu",
            "sM_WhatsappId": "999693860",
            "latitude": -12.0750562,
            "longitude": -77.08071819999999
        },
        {
            "direccionId": 21,
            "usuarioId": 18,
            "direccion_Direccion": "Av. Universitaria 53, San Miguel 15088, Perú",
            "direccionPiso": "1",
            "direccionTelefono": "4888381",
            "direccionHorario": "8:00 - 9:00",
            "nombresComercial": "Bata",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_18.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_18.png",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "BataPeru",
            "sM_InstagramId": "bata.peru",
            "sM_WhatsappId": "+51999693860",
            "latitude": -12.0761542,
            "longitude": -77.083643
        },
        {
            "direccionId": 22,
            "usuarioId": 18,
            "direccion_Direccion": "Jiron Jose Galvez 522 - B",
            "direccionPiso": "1",
            "direccionTelefono": "4888381",
            "direccionHorario": "11:00 am a 9:00 pm",
            "nombresComercial": "Bata",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_18.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_18.png",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "BataPeru",
            "sM_InstagramId": "bata.peru",
            "sM_WhatsappId": "+51999693860",
            "latitude": -12.0903509,
            "longitude": -77.07283799999999
        },
        {
            "direccionId": 23,
            "usuarioId": 18,
            "direccion_Direccion": "Av. La Mar 2275, San Miguel",
            "direccionPiso": "2",
            "direccionTelefono": "",
            "direccionHorario": "10:30 am 20:30",
            "nombresComercial": "Bata",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_18.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_18.png",
            "galeriaId": 0,
            "galeriaDescripcion": "[No posee Galeria]",
            "galeria_Direccion": null,
            "sM_FacebookId": "BataPeru",
            "sM_InstagramId": "bata.peru",
            "sM_WhatsappId": "+51999693860",
            "latitude": -12.0749941,
            "longitude": -77.08168979999999
        },
        {
            "direccionId": 1,
            "usuarioId": 1,
            "direccion_Direccion": "Av. Las Carmelias 234",
            "direccionPiso": "Piso 1",
            "direccionTelefono": "940193461",
            "direccionHorario": "Horario 8:00 a.m. a 10:00 p.m.",
            "nombresComercial": "Victors Nombre Comercial",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_1.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_1.png",
            "galeriaId": 1,
            "galeriaDescripcion": "Galeria La ratonera",
            "galeria_Direccion": null,
            "sM_FacebookId": "alumnodemichi",
            "sM_InstagramId": "victorbernedot",
            "sM_WhatsappId": "992269960",
            "latitude": -12.0931147,
            "longitude": -77.0293717
        },
        {
            "direccionId": 2,
            "usuarioId": 2,
            "direccion_Direccion": "Av. Las Carmelias 234",
            "direccionPiso": "Piso 2",
            "direccionTelefono": "940193462",
            "direccionHorario": "Horario 8:00 a.m. a 10:00 p.m.",
            "nombresComercial": "Angelas Flowers",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/fu_vestidorojo.jpg",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/logoAngela.jpeg",
            "galeriaId": 2,
            "galeriaDescripcion": "Galeria FashionIsBeauty",
            "galeria_Direccion": null,
            "sM_FacebookId": null,
            "sM_InstagramId": null,
            "sM_WhatsappId": null,
            "latitude": -12.0931147,
            "longitude": -77.0293717
        },
        {
            "direccionId": 4,
            "usuarioId": 1,
            "direccion_Direccion": "Av. Las Carmelias 234",
            "direccionPiso": "2",
            "direccionTelefono": "940193470",
            "direccionHorario": "Horario 8:00 a.m. a 10:00 p.m.",
            "nombresComercial": "Victors Nombre Comercial",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_1.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_1.png",
            "galeriaId": 3,
            "galeriaDescripcion": "Galeria La Fontana",
            "galeria_Direccion": null,
            "sM_FacebookId": "alumnodemichi",
            "sM_InstagramId": "victorbernedot",
            "sM_WhatsappId": "992269960",
            "latitude": -12.0931147,
            "longitude": -77.0293717
        },
        {
            "direccionId": 6,
            "usuarioId": 1,
            "direccion_Direccion": "Jr, Jirón Hipólito Unanue 1568, La Victoria 15018, Peru",
            "direccionPiso": "Sotano",
            "direccionTelefono": "940193471",
            "direccionHorario": "Horario 8:00 a.m. a 10:00 p.m.",
            "nombresComercial": "Victors Nombre Comercial",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/UserPhoto_1.png",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/UserLogo_1.png",
            "galeriaId": 3,
            "galeriaDescripcion": "Galeria La Fontana",
            "galeria_Direccion": null,
            "sM_FacebookId": "alumnodemichi",
            "sM_InstagramId": "victorbernedot",
            "sM_WhatsappId": "992269960",
            "latitude": -12.0751071,
            "longitude": -77.0803832
        },
        {
            "direccionId": 10,
            "usuarioId": 2,
            "direccion_Direccion": "Jr, Jirón Hipólito Unanue 1568, La Victoria 15018, Peru",
            "direccionPiso": "Piso 1",
            "direccionTelefono": "TelefonoNuevo",
            "direccionHorario": "HorarioNuevo",
            "nombresComercial": "Angelas Flowers",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/fu_vestidorojo.jpg",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/logoAngela.jpeg",
            "galeriaId": 3,
            "galeriaDescripcion": "Galeria La Fontana",
            "galeria_Direccion": null,
            "sM_FacebookId": null,
            "sM_InstagramId": null,
            "sM_WhatsappId": null,
            "latitude": -12.0931147,
            "longitude": -77.0293717
        },
        {
            "direccionId": 102,
            "usuarioId": 23,
            "direccion_Direccion": "Jr, Jirón Hipólito Unanue 1568, La Victoria 15018, Peru",
            "direccionPiso": "Piso 1",
            "direccionTelefono": "TelefonoNuevo",
            "direccionHorario": "HorarioNuevo",
            "nombresComercial": "Angelas Flowers",
            "fotoUser": "https://gamarraappstorage.blob.core.windows.net/imagenesusuarios/fu_vestidorojo.jpg",
            "logoUser": "https://gamarraappstorage.blob.core.windows.net/logosusuarios/logoAngela.jpeg",
            "galeriaId": 3,
            "galeriaDescripcion": "Galeria La Fontana",
            "galeria_Direccion": null,
            "sM_FacebookId": null,
            "sM_InstagramId": null,
            "sM_WhatsappId": null,
            "latitude": -11.9654429,
            "longitude": -76.9942375
        }
    ];
    localStorage.setItem('stores_data', JSON.stringify(stores_data));
}